{
  config,
  lib,
  pkgs,
  ...
}:
let
  dotfilesDir = "${config.home.homeDirectory}/.dotfiles";
  mkLink = relPath: config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/${relPath}";
  mkConfigLink = name: { ".config/${name}".source = mkLink "${name}/.config/${name}"; };

  # Directories to stow from dotfiles repo.
  configLinks = [
    "agents"
    "bat"
    "btop"
    "eza"
    "fastfetch"
    "git"
    "npm"
    "nvim"
    "opencode"
    "starship"
    "yazi"
    "zsh"
  ]
  ++ lib.optionals config.dandyrow.hasDesktop [ "kitty" ];
in
{
  home.file = lib.mkMerge (
    # Symlinked from the ~/.dotfiles clone created by the clone-dotfiles adapters.
    map mkConfigLink configLinks
    ++ [
      # Work identity + no GPG signing, pulled into git via includeIf for ~/Projects/work/.
      {
        "Projects/work/.gitconfig".text = ''
          [user]
            name = Daniel Lowry
            email = daniel.lowry@kainos.com

          [commit]
            gpgSign = false

          [tag]
            gpgSign = false
        '';
      }

      # Per-file, not whole-dir: gpg needs 700 on the dir and keeps runtime files (sockets, keyrings) there.
      {
        ".local/share/gnupg/gpg.conf".source = mkLink "gnupg/.local/share/gnupg/gpg.conf";
        ".local/share/gnupg/gpg-agent.conf".source = mkLink "gnupg/.local/share/gnupg/gpg-agent.conf";
        ".config/copilot/mcp-config.json".source = mkLink "copilot/.config/copilot/mcp-config.json";

        # Copilot only reads instructions from $COPILOT_HOME/copilot-instructions.md — no home-level AGENTS.md.
        ".config/copilot/copilot-instructions.md".source =
          config.lib.file.mkOutOfStoreSymlink "${config.xdg.configHome}/agents/nix-native-deps.md";
      }

      # Per-file so HM can also own the Nix-generated plugins.conf in this dir.
      {
        ".config/tmux/tmux.conf".source = mkLink "tmux/.config/tmux/tmux.conf";
        ".config/tmux/tmux-yank.sh".source = mkLink "tmux/.config/tmux/tmux-yank.sh";
        ".config/tmux/plugins.conf".text = ''
          # Generated by home-manager — do not edit
          set -g @resurrect-dir '$HOME/.local/share/tmux/resurrect'
          set -g @resurrect-capture-pane-contents 'on'
          set -g @continuum-restore 'on'
          run-shell ${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux
          run-shell ${pkgs.tmuxPlugins.continuum}/share/tmux-plugins/continuum/continuum.tmux
        '';
      }
    ]
  );
}
