format = """
$username\
$hostname\
$directory\
$character"""

right_format = """
$git_branch\
$git_state\
$git_status\
$c\
$docker_context\
$golang\
$haskell\
$java\
$nodejs\
$php\
$python\
$rust\
$terraform\
$cmd_duration\
$status"""

add_newline = false
continuation_prompt = "[>](yellow) "
palette = "catppuccin_mocha"

[username]
format = '[$user]($style) '

[hostname]
format = '[$ssh_symbol](bold green) [$hostname]($style) '
ssh_symbol = '@'

[directory]
truncation_symbol = '.../'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'purple'

[c]
format = '[$symbol($version(-$name))]($style) '

[docker_context]
format = '[$symbol$context]($style) '

[golang]
format = '[$symbol($version)]($style) '

[haskell]
format = '[$symbol($version)]($style) '

[java]
format = '[$symbol($version)]($style) '

[nodejs]
format = '[$symbol($version)]($style) '

[php]
format = '[$symbol($version)]($style) '

[python]
format = '[$symbol($version)( \($virtualenv\))]($style) '

[rust]
format = '[$symbol($version)]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[cmd_duration]
format = '[$duration]($style) '

[status]
format = '[$symbol $status]($style) '
symbol = '✖'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
white = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
cyan = "#74c7ec"
purple = "#cba6f7"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
black = "#1e1e2e"
