---
- name: Install Neovim dependencies
  ansible.builtin.package:
    name:
      - neovim
      - curl
      - wget
      - unzip
      - tar
      - gzip
      - ripgrep
      - wl-clipboard
      - git
      - ttf-dejavu-nerd
      - python
      - python-pip
      - github-cli
      - npm
      - gcc
      - codespell
      - stylua
      - actionlint
      - ansible-lint
      - yamllint
      - yamlfmt
      - eslint
    state: present
  become: true

- name: Stow Neovim dotfiles
  ansible.builtin.include_role:
    name: dandyrow.linux.stow_dotfiles
  vars:
    dotfiles_remote_repo: https://github.com/dandyrow/dotfiles
    dotfiles_to_install:
      - neovim
      - gnupg

- name: Find gnupg directories
  find:
    paths: ~/.local/share/gnupg
    recurse: true
    file_type: directory
  register: gnupg_dirs

- name: Change directory permissions to 700
  file:
    path: "{{ item.path }}"
    mode: '0700'
  loop: "{{ gnupg_dirs.files }}"

- name: Find gnupg files
  find:
    paths: ~/.local/share/gnupg
    recurse: true
    file_type: file
  register: gnupg_files

- name: Change file permissions to 600
  file:
    path: "{{ item.path }}"
    mode: '0600'
  loop: "{{ gnupg_files.files }}"
