---
- name: Install Neovim dependencies
  ansible.builtin.package:
    name:
      - neovim
      - curl
      - wget
      - unzip
      - tar
      - gzip
      - ripgrep
      - wl-clipboard
      - git
      - ttf-dejavu-nerd
      - python
      - python-pip
      - github-cli
      - npm
      - gcc
      - codespell
      - stylua
      - actionlint
      - ansible-lint
      - yamllint
      - yamlfmt
      - eslint
    state: present
  become: true

- name: Stow Neovim dotfiles
  ansible.builtin.include_role:
    name: dandyrow.linux.stow_dotfiles
  vars:
    dotfiles_remote_repo: https://github.com/dandyrow/dotfiles
    dotfiles_to_install: neovim
