---
- name: Install Tmux dependencies
  ansible.builtin.package: tmux
  state: present

- name: Stow Tmux dotfiles
  ansible.builtin.include_roles:
    name: dandyrow.linux.stow_dotfiles
  vars:
    dotfiles_remote_repo: https://github.com/dandyrow/dotfiles
    dotfiles_to_install: tmux
