---
- name: Install Zellij dependencies
  ansible.builtin.package: zellij
  state: present

- name: Stow Zellij dotfiles
  ansible.builtin.include_roles:
    name: dandyrow.linux.stow_dotfiles
  vars:
    dotfiles_remote_repo: https://github.com/dandyrow/dotfiles
    dotfiles_to_install: zellij
