---
- name: Install ZSH dependencies
  ansible.builtin.package:
    name:
      - zsh
      - fastfetch
      - fzf
      - exa
      - starship
      - zoxide
      - ttf-dejavu-nerd
    state: present
  become: true

- name: Install pkgfile for Arch command not found support
  ansible.builtin.package:
    name: pkgfile
    state: present
  when: ansible_distribution == "Archlinux"
  become: true

- name: Set ZSH as default shell
  ansible.builtin.include_role:
    name: dandyrow.linux.zsh
  vars:
    default_shell: true
    xdg_directory: true

- name: Stow ZSH dotfiles
  ansible.builtin.include_role:
    name: dandyrow.linux.stow_dotfiles
  vars:
    dotfiles_remote_repo: https://github.com/dandyrow/dotfiles
    dotfiles_to_install:
      - zsh
      - starship
      - fastfetch
