{
  config,
  lib,
  pkgs,
  ...
}:
let
  dotfilesDir = "${config.home.homeDirectory}/.dotfiles";
  mkLink = relPath: config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/${relPath}";
  mkConfigLink = name: { ".config/${name}".source = mkLink "${name}/.config/${name}"; };

  # Pinned alongside nixpkgs herdr so integration assets match the installed binary.
  herdrSrc = pkgs.fetchFromGitHub {
    owner = "herdrdev";
    repo = "herdr";
    rev = "v0.8.2";
    hash = "sha256-sEGIN3dLZasaHob3EHscWBCIQHflMQVchYmzgsETDk4=";
  };

  # Directories to stow from dotfiles repo.
  configLinks = [
    "agents"
    "bat"
    "btop"
    "eza"
    "fastfetch"
    "git"
    "herdr"
    "npm"
    "nvim"
    "starship"
    "yazi"
    "zsh"
  ]
  ++ lib.optionals config.dandyrow.hasDesktop [ "kitty" ];
in
{
  home.file = lib.mkMerge (
    # Symlinked from the ~/.dotfiles clone created by the clone-dotfiles adapters.
    map mkConfigLink configLinks
    ++ [
      # Work identity + no GPG signing, pulled into git via includeIf for ~/Projects/work/.
      {
        "Projects/work/.gitconfig".text = ''
          [user]
            name = Daniel Lowry
            email = daniel.lowry@kainos.com

          [commit]
            gpgSign = false

          [tag]
            gpgSign = false
        '';
      }

      # Per-file, not whole-dir: gpg needs 700 on the dir and keeps runtime files (sockets, keyrings) there.
      {
        ".local/share/gnupg/gpg.conf".source = mkLink "gnupg/.local/share/gnupg/gpg.conf";
        ".local/share/gnupg/gpg-agent.conf".source = mkLink "gnupg/.local/share/gnupg/gpg-agent.conf";
        ".local/share/agents/skills/unslop".source = mkLink "agents/.local/share/agents/skills/unslop";
        ".config/copilot/mcp-config.json".source = mkLink "copilot/.config/copilot/mcp-config.json";

        # Copilot only reads instructions from $COPILOT_HOME/copilot-instructions.md — no home-level AGENTS.md.
        ".config/copilot/copilot-instructions.md".source =
          config.lib.file.mkOutOfStoreSymlink "${config.xdg.configHome}/agents/nix-native-deps.md";

        # herdr session-restore hook, mirrors `herdr integration install copilot` under COPILOT_HOME.
        ".config/copilot/hooks/herdr-agent-state.sh".source =
          "${herdrSrc}/src/integration/assets/copilot/herdr-agent-state.sh";
        ".config/copilot/settings.json".text = ''
          {
            "hooks": {
              "SessionStart": [
                {
                  "type": "command",
                  "bash": "bash '${config.home.homeDirectory}/.config/copilot/hooks/herdr-agent-state.sh'",
                  "timeoutSec": 10
                }
              ]
            }
          }
        '';
      }

      # Per-file so the herdr plugin (store-linked) can sit beside repo-owned opencode config.
      {
        ".config/opencode/opencode.json".source = mkLink "opencode/.config/opencode/opencode.json";
        ".config/opencode/tui.json".source = mkLink "opencode/.config/opencode/tui.json";
        ".config/opencode/lib/nix-native-guard.ts".source =
          mkLink "opencode/.config/opencode/lib/nix-native-guard.ts";
        ".config/opencode/plugins/nix-native-guard.ts".source =
          mkLink "opencode/.config/opencode/plugins/nix-native-guard.ts";
        ".config/opencode/plugins/terminal-bell.ts".source =
          mkLink "opencode/.config/opencode/plugins/terminal-bell.ts";
        ".config/opencode/test/nix-native-guard.test.ts".source =
          mkLink "opencode/.config/opencode/test/nix-native-guard.test.ts";
        ".config/opencode/plugins/herdr-agent-state.js".source =
          "${herdrSrc}/src/integration/assets/opencode/herdr-agent-state.js";
      }

      # Per-file so HM can also own the Nix-generated plugins.conf in this dir.
      {
        ".config/tmux/tmux.conf".source = mkLink "tmux/.config/tmux/tmux.conf";
        ".config/tmux/tmux-yank.sh".source = mkLink "tmux/.config/tmux/tmux-yank.sh";
        ".config/tmux/plugins.conf".text = ''
          # Generated by home-manager — do not edit
          set -g @resurrect-dir '$HOME/.local/share/tmux/resurrect'
          set -g @resurrect-capture-pane-contents 'on'
          set -g @continuum-restore 'on'
          run-shell ${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux
          run-shell ${pkgs.tmuxPlugins.continuum}/share/tmux-plugins/continuum/continuum.tmux
        '';
      }
    ]
  );
}
