{
  config,
  lib,
  pkgs,
  ...
}:
let
  dotfilesDir = "${config.home.homeDirectory}/.dotfiles";
  mkLink = relPath: config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/${relPath}";
in
{
  home.file = {
    ".config/tmux/tmux.conf".source = mkLink "tmux/.config/tmux/tmux.conf";
    ".config/tmux/tmux-yank.sh".source = mkLink "tmux/.config/tmux/tmux-yank.sh";
    ".config/tmux/plugins.conf".text = ''
      # Generated by home-manager — do not edit
      set -g @resurrect-dir '$HOME/.local/share/tmux/resurrect'
      set -g @resurrect-capture-pane-contents 'on'
      set -g @continuum-restore 'on'
      run-shell ${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux
      run-shell ${pkgs.tmuxPlugins.continuum}/share/tmux-plugins/continuum/continuum.tmux
    '';
  };
}
